export enum MessageType {
  SEND_REQUEST = 'SEND_REQUEST',
  API_RESPONSE = 'API_RESPONSE',
  SAVE_COLLECTION = 'SAVE_COLLECTION',
  GET_COLLECTIONS = 'GET_COLLECTIONS',
  COLLECTIONS_LIST = 'COLLECTIONS_LIST',
  DELETE_COLLECTION = 'DELETE_COLLECTION',
  ADD_REQUEST_TO_COLLECTION = 'ADD_REQUEST_TO_COLLECTION',
  GET_HISTORY = 'GET_HISTORY',
  HISTORY_LIST = 'HISTORY_LIST',
  CLEAR_HISTORY = 'CLEAR_HISTORY',
  SAVE_TOKEN = 'SAVE_TOKEN',
  GET_TOKENS = 'GET_TOKENS',
  TOKENS_LIST = 'TOKENS_LIST',
  DELETE_TOKEN = 'DELETE_TOKEN',
  SET_ACTIVE_TOKEN = 'SET_ACTIVE_TOKEN',
  PROMPT_COLLECTION_NAME = 'PROMPT_COLLECTION_NAME',
  PROMPT_TOKEN = 'PROMPT_TOKEN'
}