export enum MessageType {
  SEND_REQUEST = 'SEND_REQUEST',
  API_RESPONSE = 'API_RESPONSE',
  SAVE_COLLECTION = 'SAVE_COLLECTION',
  GET_COLLECTIONS = 'GET_COLLECTIONS',
  COLLECTIONS_LIST = 'COLLECTIONS_LIST',
  DELETE_COLLECTION = 'DELETE_COLLECTION',
  ADD_REQUEST_TO_COLLECTION = 'ADD_REQUEST_TO_COLLECTION',  // new
  GET_HISTORY = 'GET_HISTORY',
  HISTORY_LIST = 'HISTORY_LIST',
  CLEAR_HISTORY = 'CLEAR_HISTORY'
}